### ISSUE TITLE
Bug regarding user form

### ISSUE THREAD

**Issue by calvinti12** [callmekungfu/secret-santa-for-facebook-messenger#1]
Hey can you help with setting up the bot  I already  deployed it on heroku  but it’s not working as it should   It Keep sending me back message like this... You sent the message: "Join now".

**Comment by callmekungfu** [comment]
Hi there, I haven't deployed this to any server yet. But I am assuming that this is because I used postbacks to navigate the bot, which means there is a persistent menu that needs to be implemented. You can find the code for the persistent menu in the repository, the file name is called `persistent-menu.json`.

You can read more about messenger persistent menu here: https://developers.facebook.com/docs/messenger-platform/send-messages/persistent-menu

**Comment by calvinti12** [comment]
Thank you very much will you let us know when you deploy it on a server

**Comment by callmekungfu** [comment]
You are welcomed.

**Comment by calvinti12** [comment]
Unable to add a party now  keep focusing on the time for me to import the time.. And when starting a party always get this TypeError: Cannot read property 'name' of null
The party will start but the message will not be sent out and it also happens when you hit MY Recipients it cause the App to crush and not send message I have tested it with One of my friends on Facebook but now we cannot go Friday because we cannot create a new party Just thought you would like to know

**Comment by callmekungfu** [comment]
Hi there, can you provide me with more detailed error logs regarding starting the party?

Thanks for the suggestion regarding creating the party section, I will make changes to form in the next update.

I also patched "my recipient" part, it will be up relatively shortly.

Thank you again for doing a bug report for me, I cannot be more grateful!

**Comment by calvinti12** [comment]
I will do some more testing and send you report

**Comment by calvinti12** [comment]
Unable to get pass create party  keep getting a message saying Enter a valid value

**Comment by calvinti12** [comment]
![aeeea12b-037c-4a05-a48a-98eb9f745aac](https://user-images.githubusercontent.com/26354540/49195725-47138a00-f356-11e8-9561-c9026d648c9c.png)

**Comment by callmekungfu** [comment]
Interesting issue. Allow me to take some time to look into it.

**Comment by calvinti12** [comment]
Only started when you implemented the security update

**Comment by callmekungfu** [comment]
Yup, that's the update that I added validation forms, I did some testing and found a few more bugs in the input form. thanks again for the repot.

**Comment by callmekungfu** [comment]
Sorry for the delay I have fixed the bug, please try it out, if the problem still persists please let me know.

**Comment by calvinti12** [comment]
![d205e8c5-34ac-4804-9464-b05347b2ee9e](https://user-images.githubusercontent.com/26354540/49333382-ea011980-f58b-11e8-901c-a6c6f7dc2f4b.png)

**Comment by calvinti12** [comment]
After hearing create  party It does not do anything

**Comment by calvinti12** [comment]
I fixed it I had to put my App ID In

**Comment by calvinti12** [comment]
Everything seems to be working better now Is it possible for you to add a delete button on party detail page so that we can delete a party

**Comment by calvinti12** [comment]
Any update on the wish list feature

**Comment by callmekungfu** [comment]
Sorry I was recently busy with exams, I will be working on essential features first: 

- Profile management
- Party management
- Security Update
- Help and other essentials

Then I will start working on the wishlist.

**Comment by callmekungfu** [comment]
Hi Calvin,

Just to let you know, I have updated the app with wishlist and profile management functions, you can go try it out!

**Comment by calvinti12** [comment]
I have tried but for some reason it would not let me create a party

**Comment by callmekungfu** [comment]
Oh yeah I'm updating the system to tokenize API access, you need to create another environmental variable called `JWT_CERT` with any string as the value.

**Comment by calvinti12** [comment]
The only error that I’m having right now is when I delete a party and I hit My Recipients It crashes the app even when I create a new party

**Comment by callmekungfu** [comment]
I see, I will look into it as soon as possible.

**Comment by calvinti12** [comment]
Any luck

**Comment by callmekungfu** [comment]
Yup I understand the issue and is working on a fix, as for why it crashes when you create a new party, it is likely because you don't have a `JWT_CERT` defined in your environmental variables.

**Comment by calvinti12** [comment]
JWT_CERT  I understood that part and I got it fixed but issue still remains after deleting a party if you hit My Recipents  at crash

**Comment by calvinti12** [comment]
Wishlist: 
- [object Object]

**Comment by calvinti12** [comment]
Everything works better with the update there’s one problem though  when someone add a Wishlist the other person sees this

**Comment by calvinti12** [comment]
Wishlist: 
- [object Object]

**Comment by callmekungfu** [comment]
ah ya, good catch, I will fix that asap. Just my sloppy coding lol
